### ISSUE TITLE
Questions about booking password

### ISSUE THREAD

**Issue by hezy29** [dominicarrojado/japan-visa-appointment-booking-system-notifications#1]
After receiving the available slot email there goes a url link, but the url link asks a password to login. Does that mean this slot has been booked by others?

<img width="685" alt="image" src="https://user-images.githubusercontent.com/67768189/229031426-716b8de4-75f9-4915-8df0-62714229d9be.png">

<img width="534" alt="image" src="https://user-images.githubusercontent.com/67768189/229031515-6c922315-cb71-418f-b12f-aa8d199e0b68.png">

**Comment by dominicarrojado** [comment]
Hey, seems like the embassy has added the password protection for this specific booking page. The other booking pages should still be available without password but currently fully booked.

**Comment by hezy29** [comment]
Got it! Thanks for your clarification!
