### ISSUE TITLE
Keep Generating "Oops! Something went wrong. Please try again." Error

### ISSUE THREAD

**Issue by qkyang** [dominicarrojado/japan-visa-appointment-booking-system-notifications#2]
I am not that familiar with Node.js or front end dev, so bare with me if I raised a silly question.

Upon successful installation, I started the dev server and the webpage could be successfully shown on http://localhost:3000/.
However, it keeps generating "Oops! Something went wrong. Please try again." error. Tried several different email addresses, different browsers & incognito mode.

Would be appreciated if you could possibly take a look!

**Comment by dominicarrojado** [comment]
Hi @qkyang, you can visit the actual website https://dominicarrojado.com/japan-visa-appointment-booking-system-notifications/ if you want to subscribe to the service. 🙂 This repository only includes the front-end hence the error. Hope it helps!
